Main pages
UREYPRICE/microVerseCapStoneProject pull request #4
Opened 2022-10-20 14:15 UTC by UREYPRICE

Hey Reviewer,

I have set up a "microVerseCapStoneProject" repository. I was required to do following tasks on the new main-page branch I was required to do the following tasks:

General Tasks:

    1. Documented a professional README.md.
    2. Included a .gitignore file.
    3. Set up a linter for HTML, CSS and JS make sure that any files that are not relevant are ignored by git.
    4. Added a descriptive README file to the project.

**Project Requirements:**

You should build only these 2 pages:

            1. The home page.
            2. The about page.

Each of these pages should have versions for 2 different screen sizes:

              1. Mobile: up to 768px wide.
              2. Desktop: 768px or wider.

Interactions

Links

              1. The home page should have a link in the menu to the about page.
              2. The logo in the header links to the home page.
              3. Mobile menu
              4. When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
              5. There are no guidelines for the mobile menu in the docs, but you should implement it so it is consistent with the design (colors, typography, spacings, etc.).
              6. The mobile menu should have a close (X) button that closes the menu.
              7. Dynamic page

            1. The section "Featured speakers" should be created dynamically in JavaScript.
            2. You should use a JavaScript variable with the data about the speakers and use it when the page loads to create the HTML for this section dynamically.
            
            
  [Recorded Demo](https://photos.app.goo.gl/FQXk2Yiw3FeWTa3U9)

2022-10-20 17:40 UTC, codecaiine requested changes
Hi @UREYPRICE , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-10-20 17:40 UTC, codecaiine commented on README.md
> +- Content of the page is taken from [Global AI Summit](https://globalaisummit.org/en/default.aspx) webpage.
- [ ] Great job but I can not find a presentation video of your project. Please record a maximum 5 mins video presenting the features of the project you built as required for this project :+1: 
![Screenshot from 2022-10-20 15-45-10](https://user-images.githubusercontent.com/6615394/196996460-fe0a77f2-d190-40f3-86a9-d1945102cc73.png)

2022-10-20 17:40 UTC, codecaiine commented on README.md
> +
- [ ] Think you could have made your project description more descriptive . You can add more details about your project and what is the purpose of this project in order to make your readme more professional :smile:

2022-10-20 17:40 UTC, codecaiine commented on README.md
> +This project is available as open source under the terms of [MIT license](https://choosealicense.com/licenses/mit/).
- [ ] Your project doesn't have a personal license. Please create a Licence file in your repo root and copy the example from this [MIT license](https://choosealicense.com/licenses/mit/), customize it by adding your name and add the link in your readme to make it more professional :+1:

2022-10-20 17:40 UTC, codecaiine commented on README.md
> +
- [ ] Please add a link to your project issue in case someone would like to contribute to your project :smile:

2022-10-20 17:40 UTC, codecaiine commented on about.html
> +    </div>
- [ ] Good job with your navbar but I think you can move your menu inside `nav` tag for the semantic reason also please work on your design in order to make it similar to the original template :+1: 

### Original design
![Screenshot from 2022-10-19 20-04-46](https://user-images.githubusercontent.com/6615394/196793670-bdd829a7-a34e-4f9f-9d89-eb684f2fa757.png)

### Your design
![Screenshot from 2022-10-20 16-19-05](https://user-images.githubusercontent.com/6615394/197004991-216dea07-63ff-44c7-87f3-12df32a93bc9.png)

2022-10-20 17:40 UTC, codecaiine commented on index.html
> +
- [ ]  I think for your desktop version of the **main program** card you need to adjust your design Please make them similar to the original design as much as possible :

- [ ] Please make sure that when we hover your card we have the same effect as defined on the original. Please fix it to be the same in the desktop version :smile: 


#### Your design
![Screenshot from 2022-10-20 16-32-09](https://user-images.githubusercontent.com/6615394/197006820-27d59530-82dd-451d-8ac3-afba55c31196.png)


#### Original design
![TTTTd](https://user-images.githubusercontent.com/6615394/181399594-50527205-226e-4f21-bdca-f99ed8c9459f.png)

2022-10-20 17:40 UTC, codecaiine commented on index.html
> +
- [ ] Good job so far with the feature film section :+1:  But I think you should display 6 movies card instead of 2 as defined in the original design. Remember that you need o have a similar design as much as possible. Please fix it  and make sure that you have the same background color for this section :smile: 

### Original design
![Screenshot from 2022-07-28 01-20-01](https://user-images.githubusercontent.com/6615394/181400202-3d0212ba-89a0-4cf1-86f9-8cfb2b867759.png)

### Your design
![Screenshot from 2022-10-20 16-39-27](https://user-images.githubusercontent.com/6615394/197008163-8a341526-ddf3-4979-8752-ff46bd8f410f.png)

2022-10-20 17:40 UTC, codecaiine commented on index.html
> +      </div>
- [ ] Please add the orange button **JOIN CC GLOBAL SUMMIT** as defined on the original design and work in the design in order to make it similar to the original design :+1: 

### Your design
![Screenshot from 2022-10-20 16-50-52](https://user-images.githubusercontent.com/6615394/197010892-2cd38080-df26-4b33-88a9-0408a52e93ba.png)


### Original Design
![Screenshot from 2022-07-27 19-32-53](https://user-images.githubusercontent.com/6615394/181357245-95b84fc9-044a-4fa9-b7dc-108956f96c40.png)

2022-10-20 17:40 UTC, codecaiine commented on index.html
> +      </div>
- [x] There is a big difference between your design for the featured film section and the original design Please make this section similar to the original design cause you need to stick it as much as possible :+1: 
#### Original design
![Screenshot from 2022-07-28 02-24-52](https://user-images.githubusercontent.com/6615394/181406919-da51bdab-31ff-4341-bd31-ccb0f57d92e2.png)

#### Your design
![Screenshot from 2022-10-20 16-54-58](https://user-images.githubusercontent.com/6615394/197013065-d9b44d34-d9b0-49cc-9639-1c073dfb6ef4.png)

![Screenshot from 2022-10-20 16-54-47](https://user-images.githubusercontent.com/6615394/197012791-3a2cae56-f96c-4f29-bade-4225ce91a885.png)

2022-10-20 17:40 UTC, codecaiine commented on index.html
> +            <img src="img/headiline-text.png" alt="heding text via image">
- [ ] I noticed that you use an image for this part. It is a bad practice Please make sure that you use a small line of text and for the page title please use a heading tag `hx` for them. Don't forget to use `h1` tag only one time and no more than one time in your both index.html and about.html :+1: 
Example 
```
<hx> Hello Sharing the world <hx>
<h1>CREATIVE COMMONS GLOBAL SUMMIT 2015 <h1>
```

2022-10-20 17:40 UTC, codecaiine commented on about.html
> +            <img class="about-title-text" src="img/about-title.png" alt="title heading text via image">
- [ ] I noticed that you use an image for this part. It is a bad practice Please make sure that you use a small line of text and for the page title please use a heading tag `hx` for them. Don't forget to use `h1` tag only one time and no more than one time in your both index.html and about.html :+1: 
Example 
```
<hx> Hello Sharing the world <hx>
<h1>CREATIVE COMMONS GLOBAL SUMMIT 2015 <h1>
```

2022-10-20 17:40 UTC, codecaiine commented on script.js
> +</section>`;
- [ ] Please make sure to create an array of objects for your speaker's list and store the data in an object. You should use a JavaScript variable with the data about the speakers and use it when the page loads to create the HTML for this section dynamically as required for this project :smile: 

check the example below :arrow_down: 

```

const speakers = [
  {
    title: 'Web Development',
    image: './assets/icon/icon-web.png',
    content:
      'Bin Tech is a nationwide innovation inclusive environment designed to ensure students.',
  },
  {
    title: 'Mobile App',
    image: './assets/icon/icon-mob.png',
    content:
      'Bin Tech is a nationwide innovation inclusive environment designed to ensure students.',
  },
.........
]
```

```
const showCards = (i) => {
  cards.innerHTML += `<article class="card">
  <img class="card-img" src=${technologies[i].image} alt="" />
<h3 class="card-title">${technologies[i].title}</h3>
<p class="card-content">${technologies[i].content}
</p>
</article>`;
};

const showLectures = (i) => {
  feature.innerHTML += `<article class="feature-card">
<div class="feature-img">
<img
src="./assets/bg/checkerboard-squares-black-white.jpg"
alt="background"
class="bg-people"/>
<img
class="people-img"
src=${lectures[i].image}
alt="binhussen image"
/>
</div>
<div>
<h3 class="feture-name">${lectures[i].name}</h3>
<h5 class="card-title">${lectures[i].title}</h5>
<p class="card-content">
${lectures[i].content}
</p>
</div>
</article>`;
};
```

2022-10-20 17:40 UTC, codecaiine commented on about.html
> +  <script src="script.js"></script>
- [ ] Good job with your about section :+1: But please use the same background color for the recent work section as defined in the original design and make your about section similar to the original design :smile: 

### Orignal design
![Screenshot from 2022-07-27 19-41-40](https://user-images.githubusercontent.com/6615394/181358728-12e551d4-0702-4690-98cd-8848c22a07d1.png)

### Your design
![Screenshot from 2022-10-20 17-35-02](https://user-images.githubusercontent.com/6615394/197019239-d9c3e9ff-630d-47dc-895f-1d6c2273af75.png)

2022-10-21 14:26 UTC, UREYPRICE commented on index.html
> +
i didnt get this part could you please explain ?

2022-10-21 15:50 UTC, closed without merging